### ISSUE TITLE
Admin Command Bug [Server-Wide Issue]

### ISSUE THREAD

**Issue by BryceHego** [Eimras/DBR-Rebirth-Issue-Tracker#1]
**Describe the bug**
Whenever an admin uses the reward command on any player, the entire game starts to stutter. Each time after that it's used it gets worse.

**To Reproduce**
Use the reward command on one or more players

**Expected behavior**
Simply give the reward

**Additional context**
Was found when trying to mess around with reward, which puts me at fault for what happend.

**Comment by Eimras** [comment]
Unable to reproduce. Assumed invalid for now.
