### ISSUE TITLE
Build Object Doubling [BUG]

### ISSUE THREAD

**Issue by Niezann** [Eimras/DBR-Rebirth-Issue-Tracker#2]
**Describe the bug**
When you have a Obj or Edge selected as your build, and you move; you end up stacking two atop eachother. This only occurs WHEN you move to a new tile, the tile you were standing on has only one.

**To Reproduce**
Steps to reproduce the behavior: Select a object or edge from build, take a step forward and right click to see two spawned beneath you.

**Expected behavior**
To only spawn one of the objects beneath you as you move.

**Screenshots**
https://gyazo.com/8ce433118fdf39f2fff6ab75e4892b16 The tile that was moved to.
https://gyazo.com/793151557c6da064e54b42da6d7bf4b9 The tile that was stood on while selecting the edge/obj

**Additional context**
N/A

**Comment by Eimras** [comment]
Object doubling fixed.
