### ISSUE TITLE
Zanzoken Direction[BUG]

### ISSUE THREAD

**Issue by BryceHego** [Eimras/DBR-Rebirth-Issue-Tracker#3]
**Describe the bug**
When zanzokening with someone targeted, you don't seem to face them automatically.

**To Reproduce**
Zanzoken to someone that you are targeting

**Expected behavior**
Facing towards your opponent so you can lay the smack down after going behind them.

**Screenshots**
https://gyazo.com/28ac6bafedbb91972a6f8291ca9b9bee

**Additional context**
This might not even be a bug, and might just be the lack of a feature being added that I'm used to already existing.

**Comment by Eimras** [comment]
Zanzo working properly now.
