### ISSUE TITLE
Stat and BP creation issue [BUG]

### ISSUE THREAD

**Issue by Niezann** [Eimras/DBR-Rebirth-Issue-Tracker#5]
**Describe the bug**
Stats and BP don't properly set to the server standards. You get stuck at '1' for each stat besides regen and recovery. Energy stays at 100 and your BP is only to whatever your race usually starts with.

**To Reproduce**
Steps to reproduce the behavior: Create a character, I created a Tanuki which has done it twice now.

**Expected behavior**
To set my stats to 10,000 * mod and to the proper Min Base

**Screenshots**
https://gyazo.com/8824e7bea51ab56d8c31bf75c5fe9d12

**Additional context**
More people then me are also having the issue. Rewarding stats seems to fix the issue.

**Comment by Eimras** [comment]
Issue one was of my own creation when I added age selection. Was causing a runtime in the main loop preventing many things from happening, including anger updating, AFK timer working, stats and BP updating, ect.

Has been fixed.
