### ISSUE TITLE
Dragon-Dash enters CD even if not actually used [BUG]

### ISSUE THREAD

**Issue by Idefkftt** [Eimras/DBR-Rebirth-Issue-Tracker#6]
**Describe the bug**
If you use Dragon-Dash, even without a target to dash to, it will still put the skill on cooldown.

**To Reproduce**
Steps to reproduce the behavior:  Use it with no target.

**Expected behavior**
Should simply not do anything and not put it on CD.

**Comment by Nisex** [comment]
I've taken a look at it and have sent a possible solution to Sarmie. Thanks for reporting the bug.

--Nise
