### ISSUE TITLE
Sword Customization Description [BUG]

### ISSUE THREAD

**Issue by pancakepress** [Eimras/DBR-Rebirth-Issue-Tracker#8]
[BUG]
The description of the various sword attributes is cut off from the top and at the bottom. The text box is neither re-sizable nor is there a scroll bar to view the portions of the descriptions that are cut off

[Steps to Reproduce]
Create a sword, right click the item in your inventory, then select customize sword to view the prompt.

https://i.imgur.com/6roC78b.png

**Comment by Nisex** [comment]
Seen it, fixed it simply. A message was shot to Sarmie for a simple solution.

--Nise
