### ISSUE TITLE
ArcanicOrb Text[BUG]

### ISSUE THREAD

**Issue by BryceHego** [Eimras/DBR-Rebirth-Issue-Tracker#9]
**Describe the bug**
Turning the orb on and off has both messages say the orb is turning off.

**To Reproduce**
Turn orb on and off a few times

**Expected behavior**
Say it turns on when you turn it on

**Screenshots**
https://gyazo.com/649f9aa20f207cf62007490394e66fd8

**Comment by Eimras** [comment]
Fixed as of V9.4.4
